package com.vmh.mvvmjetpackcompose.core.deeplink

import android.content.Intent
import com.airbnb.deeplinkdispatch.BaseDeepLinkDelegate
import javax.inject.Inject

/**
 * Parses the deeplink carried by an [Intent] into a [DeepLinkDestination], or `null` if the intent
 * carries no data or matches no deeplink.
 *
 * Returns the module's own [DeepLinkDestination] rather than DeepLinkDispatch's `DeepLinkResult` so
 * callers never depend on the library type, keeping the layer boundary intact. Pure function (no
 * side effects, never launches an Activity), so it is easy to unit-test.
 */
interface DeepLinkResolver {
  fun resolve(intent: Intent): DeepLinkDestination?
}

internal class DefaultDeepLinkResolver @Inject constructor() : DeepLinkResolver {
  // Registry generated by DeepLinkDispatch from @DeepLinkModule + the @DeepLink declarations.
  private val delegate = BaseDeepLinkDelegate(listOf(AppDeepLinkModuleRegistry()))

  override fun resolve(intent: Intent): DeepLinkDestination? {
    val uri = intent.data ?: return null
    if (uri.scheme != DeepLinkScheme.SCHEME) return null
    val match = delegate.findEntry(uri.toString()) ?: return null
    return when (match.deeplinkEntry.uriTemplate) {
      AppDeepLinks.SEARCH_TEMPLATE ->
        DeepLinkDestination.Search(keyword = uri.getQueryParameter("keyword"))

      else -> null
    }
  }
}
